// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: bvg_departures

#include "../ui.h"

void ui_logs_screen_init(void)
{
ui_logs = lv_obj_create(NULL);
lv_obj_clear_flag( ui_logs, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_logs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_logs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ubahn = lv_img_create(ui_logs);
lv_img_set_src(ui_ubahn, &ui_img_ubahn_png);
lv_obj_set_width( ui_ubahn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ubahn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ubahn, 127 );
lv_obj_set_y( ui_ubahn, -53 );
lv_obj_set_align( ui_ubahn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ubahn, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ubahn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_heading = lv_label_create(ui_logs);
lv_obj_set_width( ui_heading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heading, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_heading, 20 );
lv_obj_set_y( ui_heading, 15 );
lv_label_set_text(ui_heading,"ESP32");
lv_obj_set_style_text_font(ui_heading, &ui_font_terminus36bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logspanel = lv_obj_create(ui_logs);
lv_obj_set_width( ui_logspanel, 447);
lv_obj_set_height( ui_logspanel, 235);
lv_obj_set_x( ui_logspanel, 0 );
lv_obj_set_y( ui_logspanel, -18 );
lv_obj_set_align( ui_logspanel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_logspanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_logspanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_set_scroll_snap_y( ui_logspanel, LV_SCROLL_SNAP_END );  // SquareLine will override this, not sure how to set it there
lv_obj_add_flag( ui_logspanel, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_logspanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_logspanel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_logspanel, 51, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_logspanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


}
