// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: bvg_departures

#include "../ui.h"

void ui_splash_screen_init(void)
{
ui_splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_splash, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_splash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_splashtitle = lv_label_create(ui_splash);
lv_obj_set_width( ui_splashtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_splashtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_splashtitle, 0 );
lv_obj_set_y( ui_splashtitle, -23 );
lv_obj_set_align( ui_splashtitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_splashtitle,"ESP32");
lv_obj_set_style_text_color(ui_splashtitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_splashtitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_splashtitle, &ui_font_robotocondensed96regular, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_splashspinner = lv_spinner_create(ui_splash,1000,90);
lv_obj_set_width( ui_splashspinner, 50);
lv_obj_set_height( ui_splashspinner, 51);
lv_obj_set_x( ui_splashspinner, 0 );
lv_obj_set_y( ui_splashspinner, 73 );
lv_obj_set_align( ui_splashspinner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_splashspinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_splashspinner, lv_color_hex(0xFFF000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_splashspinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
