// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: bvg_departures

#include "../ui.h"

void ui_mainscreen_screen_init(void)
{
ui_mainscreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_line = lv_label_create(ui_mainscreen);
lv_obj_set_width( ui_line, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_line, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_line, 20 );
lv_obj_set_y( ui_line, 30 );
lv_label_set_text(ui_line,"Linie");
lv_obj_set_style_text_font(ui_line, &ui_font_terminus28bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_direction = lv_label_create(ui_line);
lv_obj_set_width( ui_direction, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_direction, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_direction, 85 );
lv_obj_set_y( ui_direction, 0 );
lv_label_set_text(ui_direction,"Ziel");

ui_departure = lv_label_create(ui_line);
lv_obj_set_width( ui_departure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_departure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_departure, 346 );
lv_obj_set_y( ui_departure, 0 );
lv_label_set_text(ui_departure,"Abfahrt");

ui_departurespanel = lv_obj_create(ui_mainscreen);
lv_obj_set_width( ui_departurespanel, 447);
lv_obj_set_height( ui_departurespanel, 235);
lv_obj_set_x( ui_departurespanel, 0 );
lv_obj_set_y( ui_departurespanel, -20 );
lv_obj_set_align( ui_departurespanel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_departurespanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_departurespanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_departurespanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_departurespanel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_departurespanel, 51, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_departurespanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_departureitem1 = ui_departureitem_create(ui_departurespanel);
lv_obj_set_x( ui_departureitem1, -1 );
lv_obj_set_y( ui_departureitem1, -89 );



ui_departureitem2 = ui_departureitem_create(ui_departurespanel);
lv_obj_set_x( ui_departureitem2, 0 );
lv_obj_set_y( ui_departureitem2, 80 );



ui_departureitem3 = ui_departureitem_create(ui_departurespanel);
lv_obj_set_x( ui_departureitem3, 0 );
lv_obj_set_y( ui_departureitem3, -42 );



ui_departureitem4 = ui_departureitem_create(ui_departurespanel);
lv_obj_set_x( ui_departureitem4, 0 );
lv_obj_set_y( ui_departureitem4, -9 );



ui_departureitem5 = ui_departureitem_create(ui_departurespanel);
lv_obj_set_x( ui_departureitem5, 0 );
lv_obj_set_y( ui_departureitem5, 36 );



ui_departureitem6 = ui_departureitem_create(ui_departurespanel);
lv_obj_set_x( ui_departureitem6, 24 );
lv_obj_set_y( ui_departureitem6, 110 );



lv_obj_add_event_cb(ui_departurespanel, ui_event_departurespanel, LV_EVENT_ALL, NULL);

}
