// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT departureitem

lv_obj_t *ui_departureitem_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_departureitem;
cui_departureitem = lv_obj_create(comp_parent);
lv_obj_set_width( cui_departureitem, 441);
lv_obj_set_height( cui_departureitem, 38);
lv_obj_set_x( cui_departureitem, -1 );
lv_obj_set_y( cui_departureitem, -89 );
lv_obj_set_align( cui_departureitem, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_departureitem, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( cui_departureitem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_departureitem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_departureitem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_departureitem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_departureitem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_departureitem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_departureitem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_departureitem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_departureitem, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_departureitem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_departureitem, &ui_font_terminus28bold, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_departure0line;
cui_departure0line = lv_label_create(cui_departureitem);
lv_obj_set_width( cui_departure0line, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_departure0line, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_departure0line, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_departure0line,"U7");
lv_obj_set_style_text_font(cui_departure0line, &ui_font_terminus36bold, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_departure0direction;
cui_departure0direction = lv_label_create(cui_departureitem);
lv_obj_set_width( cui_departure0direction, 283);
lv_obj_set_height( cui_departure0direction, 28);
lv_obj_set_x( cui_departure0direction, 80 );
lv_obj_set_y( cui_departure0direction, 1 );
lv_obj_set_align( cui_departure0direction, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(cui_departure0direction,LV_LABEL_LONG_DOT);
lv_label_set_text(cui_departure0direction,"U Berliner Str.");

lv_obj_t *cui_departure0time;
cui_departure0time = lv_label_create(cui_departureitem);
lv_obj_set_width( cui_departure0time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_departure0time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_departure0time, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_departure0time,"4'");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DEPARTUREITEM_NUM);
children[UI_COMP_DEPARTUREITEM_DEPARTUREITEM] = cui_departureitem;
children[UI_COMP_DEPARTUREITEM_DEPARTURE0LINE] = cui_departure0line;
children[UI_COMP_DEPARTUREITEM_DEPARTURE0DIRECTION] = cui_departure0direction;
children[UI_COMP_DEPARTUREITEM_DEPARTURE0TIME] = cui_departure0time;
lv_obj_add_event_cb(cui_departureitem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_departureitem, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_departureitem_create_hook(cui_departureitem);
return cui_departureitem; 
}

