// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_DEPARTUREITEM_H
#define _UI_COMP_DEPARTUREITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT departureitem
#define UI_COMP_DEPARTUREITEM_DEPARTUREITEM 0
#define UI_COMP_DEPARTUREITEM_DEPARTURE0LINE 1
#define UI_COMP_DEPARTUREITEM_DEPARTURE0DIRECTION 2
#define UI_COMP_DEPARTUREITEM_DEPARTURE0TIME 3
#define _UI_COMP_DEPARTUREITEM_NUM 4
lv_obj_t *ui_departureitem_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
