name: Build ESP binaries
description: Build ESP binaries

runs:
    using: 'composite'
    steps:
        - uses: pnpm/action-setup@v2
          with:
              version: latest
        - name: Install node
          uses: actions/setup-node@v4
          with:
              node-version: '20.10.0'
              cache: 'pnpm'
        - name: Install frontend dependencies and build frontend
          run: |
              pnpm i
              pnpm build
          shell: bash
        - name: Cache esp-idf build
          uses: actions/cache@v3
          with:
              # TODO This caching seems useless
              path: 'build'
              key: ${{ runner.os }}-build-v7
        - name: Cache managed components
          uses: actions/cache@v3
          with:
              path: 'managed_components'
              key: ${{ runner.os }}-managed_components-${{ hashFiles('dependencies.lock') }}-v2
        - name: Address ESP-IDF component hash bug
          run: |
              rm -rf managed_components/bblanchon__arduinojson/.component_hash
          shell: bash
        - name: esp-idf build and merge firmware
          run: |
              docker run -t -e IDF_TARGET="esp32" -e GITHUB_ACTIONS=true -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" \
              -w "/app/${{ github.repository }}" espressif/idf:release-v5.1 \
              /bin/bash -c 'git config --global --add safe.directory "*" && idf.py build && cd /app/${{ github.repository }}/scripts && ./merge_firmware.sh'
          shell: bash
